INSERT INTO books (url,
                   name,
                   isbn,
                   authors,
                   number_of_pages,
                   publisher,
                   country,
                   media_type,
                   released)
        VALUES ('http://localhost:8080/api/books/1',
                'A Game of Thrones',
                '978-0553103540',
                 ARRAY ['George R. R. Martin'],
                 694,
                 'Bantam Books',
                 'United States',
                 'HARDCOVER',
                 '1996-08-01T00:00:00');

INSERT INTO books (url,
                   name,
                   isbn,
                   authors,
                   number_of_pages,
                   publisher,
                   country,
                   media_type,
                   released)
        VALUES ('http://localhost:8080/api/books/2',
                'A Clash of Kings',
                '978-0553108033',
                 ARRAY ['George R. R. Martin'],
                 768,
                 'Bantam Books',
                 'United States',
                 'HARDCOVER',
                 '1999-02-02T00:00:00')