 INSERT INTO characters (
    url,
    name,
    gender,
    culture,
    born,
    died,
    titles,
    aliases,
    father_url,
    mother_url,
    allegiances,
    tv_series,
    played_by)
 VALUES (
    'http://localhost:8080/api/characters/1',
    null,
    'FEMALE',
    'Braavosi',
    null,
    null,
    ARRAY ['The Daughter of the Dusk'],
    null,
    null,
    null,
    null,
    null,
    null
 );

 INSERT INTO characters (
    url,
    name,
    gender,
    culture,
    born,
    died,
    titles,
    aliases,
    father_url,
    mother_url,
    allegiances,
    tv_series,
    played_by)
 VALUES (
    'http://localhost:8080/api/characters/2',
    null,
    'MALE',
    null,
    null,
    null,
    ARRAY ['Hodor'],
    null,
    null,
    null,
    null,
    ARRAY ['Season 1','Season 2','Season 3','Season 4'],
    ARRAY ['Kristian Nairn']
 );

 INSERT INTO characters (
    url,
    name,
    gender,
    culture,
    born,
    died,
    titles,
    aliases,
    father_url,
    mother_url,
    allegiances,
    tv_series,
    played_by)
 VALUES (
    'http://localhost:8080/api/characters/229',
    'Lord 1',
    'MALE',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    ARRAY ['Season 1','Season 2','Season 3','Season 4'],
    null
 );
INSERT INTO characters (
    url,
    name,
    gender,
    culture,
    born,
    died,
    titles,
    aliases,
    father_url,
    mother_url,
    allegiances,
    tv_series,
    played_by)
 VALUES (
    'http://localhost:8080/api/characters/298',
    'Lord 2',
    'MALE',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    ARRAY ['Season 1','Season 2','Season 3','Season 4'],
    null
 );

 INSERT INTO characters (
     url,
     name,
     gender,
     culture,
     born,
     died,
     titles,
     aliases,
     father_url,
     mother_url,
     allegiances,
     tv_series,
     played_by)
  VALUES (
     'http://localhost:8080/api/characters/1922',
     'Heir',
     'MALE',
     null,
     null,
     null,
     null,
     null,
     null,
     null,
     null,
     ARRAY ['Season 1','Season 2','Season 3','Season 4'],
     null
  );
INSERT INTO characters (
    url,
    name,
    gender,
    culture,
    born,
    died,
    titles,
    aliases,
    father_url,
    mother_url,
    allegiances,
    tv_series,
    played_by)
 VALUES (
    'http://localhost:8080/api/characters/285',
    'Overlord 1',
    'MALE',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    ARRAY ['Season 1','Season 2','Season 3','Season 4'],
    null
 );